TrajectoryPlannerROS:
  max_vel_x: 0.4
  min_vel_x: 0.05
  max_vel_theta: 1.6
  min_in_place_vel_theta: 0.4

  acc_lim_theta: 3.2
  acc_lim_x: 2.5
  acc_lim_y: 2.5

  yaw_goal_tolerance: 0.26
  holonomic_robot: false
